### ISSUE TITLE
save dies when module is pasted into the repl

### ISSUE THREAD

**Issue by lendle** [MichaelHatherly/Lexicon.jl#33]
```jlcon
 | | |_| | | | (_| |  |  Version 0.3.7-pre+1 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d15f183 (8 days old release-0.3)
|__/                   |  x86_64-unknown-linux-gnu

julia> module MyMod

       using Docile
       @document

       # "Docstring for my module"
       # MyMod

       "Identity function"
       f(x)=x

       end

julia> using Lexicon


julia> save("mymod.md", MyMod)
INFO: Parsing documentation for MyMod.
ERROR: opening file : No such file or directory
 in open at ./iostream.jl:117
 in open at ./iostream.jl:135
 in rootast at /home/sam/.julia/v0.3/Docile/src/builddocs.jl:12
 in metadata at /home/sam/.julia/v0.3/Docile/src/interface.jl:63

julia> 
```

It works fine if I `include` a file defining the module though.

**Comment by MichaelHatherly** [comment]
The trouble here is that the `""`-style docstrings are collected after the module is loaded rather than during module parsing as is the case witjh `@doc`-style docstrings.

We need to have the path of the root file for a module to be able to collect the docs, but there's no path for a module defined in the REPL. It could be possible to get around this be looking into the `.julia_history` file, though that's not something I'd like to do if possible.

Have you got a specific use case for this that I'm missing here? Might be best to just have a better error message rather than allowing it.

**Comment by MichaelHatherly** [comment]
Commit MichaelHatherly/Docile.jl@b5e9ab459d6a6af6bc54a67cf272c6d179574320 adds a more informative error message for this. Documenting from the REPL using `@doc`-style docstrings is still supported though.

**Comment by lendle** [comment]
My use case was coming up with a minimal example for reporting #32, so no,
I don't really have one.  Thanks for fixing these so quickly!

**Comment by MichaelHatherly** [comment]
Yeah, figured that's what it probably was :)
