### ISSUE TITLE
AbstractDomains is not documented in julia0.4

### ISSUE THREAD

**Issue by zenna** [MichaelHatherly/Lexicon.jl#79]
Get the following error when trying to out Lexicon for [AbstractDomains.jl](https://github.com/zenna/AbstractDomains.jl) in julia0.4. Works fine in julia0.3

```
julia> save("Domains.md",AbstractDomains)
ERROR: ArgumentError: AbstractDomains is not documented.
 in metadata at /home/zenna/.julia/v0.4/Docile/src/interface.jl:58
 in save at /home/zenna/.julia/v0.4/Lexicon/src/render.jl:56
```

**Comment by MichaelHatherly** [comment]
Hi @zenna, since you're conditionally importing Docile [here](https://github.com/zenna/AbstractDomains.jl/blob/2aabfae07ea02af5e4552817731580eada6ea0d5/src/AbstractDomains.jl#L10) this means that Lexicon will not be able to extract the documentation in 0.4.

I'd suggest generating static docs using 0.3 for the moment rather than 0.4.

**Comment by MichaelHatherly** [comment]
If you run into further issues related to this please do reopen or ping me to reopen this issue for further discussion.
